// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: grok_credits.proto

package grok

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UsagePeriodType int32

const (
	UsagePeriodType_USAGE_PERIOD_TYPE_UNSPECIFIED UsagePeriodType = 0
	UsagePeriodType_USAGE_PERIOD_TYPE_MONTHLY     UsagePeriodType = 1
	UsagePeriodType_USAGE_PERIOD_TYPE_WEEKLY      UsagePeriodType = 2
)

// Enum value maps for UsagePeriodType.
var (
	UsagePeriodType_name = map[int32]string{
		0: "USAGE_PERIOD_TYPE_UNSPECIFIED",
		1: "USAGE_PERIOD_TYPE_MONTHLY",
		2: "USAGE_PERIOD_TYPE_WEEKLY",
	}
	UsagePeriodType_value = map[string]int32{
		"USAGE_PERIOD_TYPE_UNSPECIFIED": 0,
		"USAGE_PERIOD_TYPE_MONTHLY":     1,
		"USAGE_PERIOD_TYPE_WEEKLY":      2,
	}
)

func (x UsagePeriodType) Enum() *UsagePeriodType {
	p := new(UsagePeriodType)
	*p = x
	return p
}

func (x UsagePeriodType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UsagePeriodType) Descriptor() protoreflect.EnumDescriptor {
	return file_grok_credits_proto_enumTypes[0].Descriptor()
}

func (UsagePeriodType) Type() protoreflect.EnumType {
	return &file_grok_credits_proto_enumTypes[0]
}

func (x UsagePeriodType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UsagePeriodType.Descriptor instead.
func (UsagePeriodType) EnumDescriptor() ([]byte, []int) {
	return file_grok_credits_proto_rawDescGZIP(), []int{0}
}

type Timestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seconds       int64                  `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanos         int32                  `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	mi := &file_grok_credits_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_grok_credits_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_grok_credits_proto_rawDescGZIP(), []int{0}
}

func (x *Timestamp) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *Timestamp) GetNanos() int32 {
	if x != nil {
		return x.Nanos
	}
	return 0
}

type UsagePeriod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          UsagePeriodType        `protobuf:"varint,1,opt,name=type,proto3,enum=grok.UsagePeriodType" json:"type,omitempty"`
	Start         *Timestamp             `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End           *Timestamp             `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsagePeriod) Reset() {
	*x = UsagePeriod{}
	mi := &file_grok_credits_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsagePeriod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsagePeriod) ProtoMessage() {}

func (x *UsagePeriod) ProtoReflect() protoreflect.Message {
	mi := &file_grok_credits_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsagePeriod.ProtoReflect.Descriptor instead.
func (*UsagePeriod) Descriptor() ([]byte, []int) {
	return file_grok_credits_proto_rawDescGZIP(), []int{1}
}

func (x *UsagePeriod) GetType() UsagePeriodType {
	if x != nil {
		return x.Type
	}
	return UsagePeriodType_USAGE_PERIOD_TYPE_UNSPECIFIED
}

func (x *UsagePeriod) GetStart() *Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *UsagePeriod) GetEnd() *Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type GrokCreditsConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CreditUsagePercent float32                `protobuf:"fixed32,1,opt,name=credit_usage_percent,json=creditUsagePercent,proto3" json:"credit_usage_percent,omitempty"`
	BillingPeriodEnd   *Timestamp             `protobuf:"bytes,5,opt,name=billing_period_end,json=billingPeriodEnd,proto3" json:"billing_period_end,omitempty"`
	CurrentPeriod      *UsagePeriod           `protobuf:"bytes,8,opt,name=current_period,json=currentPeriod,proto3" json:"current_period,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GrokCreditsConfig) Reset() {
	*x = GrokCreditsConfig{}
	mi := &file_grok_credits_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrokCreditsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrokCreditsConfig) ProtoMessage() {}

func (x *GrokCreditsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_grok_credits_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrokCreditsConfig.ProtoReflect.Descriptor instead.
func (*GrokCreditsConfig) Descriptor() ([]byte, []int) {
	return file_grok_credits_proto_rawDescGZIP(), []int{2}
}

func (x *GrokCreditsConfig) GetCreditUsagePercent() float32 {
	if x != nil {
		return x.CreditUsagePercent
	}
	return 0
}

func (x *GrokCreditsConfig) GetBillingPeriodEnd() *Timestamp {
	if x != nil {
		return x.BillingPeriodEnd
	}
	return nil
}

func (x *GrokCreditsConfig) GetCurrentPeriod() *UsagePeriod {
	if x != nil {
		return x.CurrentPeriod
	}
	return nil
}

type GetGrokCreditsConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *GrokCreditsConfig     `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGrokCreditsConfigResponse) Reset() {
	*x = GetGrokCreditsConfigResponse{}
	mi := &file_grok_credits_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGrokCreditsConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGrokCreditsConfigResponse) ProtoMessage() {}

func (x *GetGrokCreditsConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grok_credits_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGrokCreditsConfigResponse.ProtoReflect.Descriptor instead.
func (*GetGrokCreditsConfigResponse) Descriptor() ([]byte, []int) {
	return file_grok_credits_proto_rawDescGZIP(), []int{3}
}

func (x *GetGrokCreditsConfigResponse) GetConfig() *GrokCreditsConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

var File_grok_credits_proto protoreflect.FileDescriptor

const file_grok_credits_proto_rawDesc = "" +
	"\n" +
	"\x12grok_credits.proto\x12\x04grok\";\n" +
	"\tTimestamp\x12\x18\n" +
	"\aseconds\x18\x01 \x01(\x03R\aseconds\x12\x14\n" +
	"\x05nanos\x18\x02 \x01(\x05R\x05nanos\"\x82\x01\n" +
	"\vUsagePeriod\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.grok.UsagePeriodTypeR\x04type\x12%\n" +
	"\x05start\x18\x02 \x01(\v2\x0f.grok.TimestampR\x05start\x12!\n" +
	"\x03end\x18\x03 \x01(\v2\x0f.grok.TimestampR\x03end\"\xbe\x01\n" +
	"\x11GrokCreditsConfig\x120\n" +
	"\x14credit_usage_percent\x18\x01 \x01(\x02R\x12creditUsagePercent\x12=\n" +
	"\x12billing_period_end\x18\x05 \x01(\v2\x0f.grok.TimestampR\x10billingPeriodEnd\x128\n" +
	"\x0ecurrent_period\x18\b \x01(\v2\x11.grok.UsagePeriodR\rcurrentPeriod\"O\n" +
	"\x1cGetGrokCreditsConfigResponse\x12/\n" +
	"\x06config\x18\x01 \x01(\v2\x17.grok.GrokCreditsConfigR\x06config*q\n" +
	"\x0fUsagePeriodType\x12!\n" +
	"\x1dUSAGE_PERIOD_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19USAGE_PERIOD_TYPE_MONTHLY\x10\x01\x12\x1c\n" +
	"\x18USAGE_PERIOD_TYPE_WEEKLY\x10\x02BKZIgithub.com/AaronFeledy/claude-usage-widget/server/internal/providers/grokb\x06proto3"

var (
	file_grok_credits_proto_rawDescOnce sync.Once
	file_grok_credits_proto_rawDescData []byte
)

func file_grok_credits_proto_rawDescGZIP() []byte {
	file_grok_credits_proto_rawDescOnce.Do(func() {
		file_grok_credits_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grok_credits_proto_rawDesc), len(file_grok_credits_proto_rawDesc)))
	})
	return file_grok_credits_proto_rawDescData
}

var file_grok_credits_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grok_credits_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grok_credits_proto_goTypes = []any{
	(UsagePeriodType)(0),                 // 0: grok.UsagePeriodType
	(*Timestamp)(nil),                    // 1: grok.Timestamp
	(*UsagePeriod)(nil),                  // 2: grok.UsagePeriod
	(*GrokCreditsConfig)(nil),            // 3: grok.GrokCreditsConfig
	(*GetGrokCreditsConfigResponse)(nil), // 4: grok.GetGrokCreditsConfigResponse
}
var file_grok_credits_proto_depIdxs = []int32{
	0, // 0: grok.UsagePeriod.type:type_name -> grok.UsagePeriodType
	1, // 1: grok.UsagePeriod.start:type_name -> grok.Timestamp
	1, // 2: grok.UsagePeriod.end:type_name -> grok.Timestamp
	1, // 3: grok.GrokCreditsConfig.billing_period_end:type_name -> grok.Timestamp
	2, // 4: grok.GrokCreditsConfig.current_period:type_name -> grok.UsagePeriod
	3, // 5: grok.GetGrokCreditsConfigResponse.config:type_name -> grok.GrokCreditsConfig
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_grok_credits_proto_init() }
func file_grok_credits_proto_init() {
	if File_grok_credits_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grok_credits_proto_rawDesc), len(file_grok_credits_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grok_credits_proto_goTypes,
		DependencyIndexes: file_grok_credits_proto_depIdxs,
		EnumInfos:         file_grok_credits_proto_enumTypes,
		MessageInfos:      file_grok_credits_proto_msgTypes,
	}.Build()
	File_grok_credits_proto = out.File
	file_grok_credits_proto_goTypes = nil
	file_grok_credits_proto_depIdxs = nil
}
